//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixLabel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BARCODE_FIXPROD_ID
    {
        public string CUST_PART_FIX { get; set; }
        public Nullable<decimal> BOXID { get; set; }
        public Nullable<decimal> PACKID { get; set; }
        public Nullable<System.DateTime> UPDT { get; set; }
        public string UPLOG { get; set; }
    }
}
